name: Java CI Group1

env:
  LOCAL_DB_URL: ${{ vars.LOCAL_DB_URL }}
  LOCAL_DB_NAME: ${{ vars.LOCAL_DB_NAME }}
  LOCAL_DB_PASS: ${{ vars.LOCAL_DB_PASS }}
  PROD_DB_URL: ${{ vars.PROD_DB_URL }}
  PROD_DB_PASS: ${{ vars.PROD_DB_PASS }}
  PROD_DB_USER: ${{ vars.PROD_DB_USER }}
  PR0D_SECURITY_PASS: ${{ vars.PR0D_SECURITY_PASS }}

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Gradle
        run: gradle clean test

      - name: Archive Rest Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: GradleReports/emailable-report.html
